namespace: "alikins"
name: "collection_reqs_test"
version: "2.1113.28"
description: "a collection with requirements.yml"
authors: ["Adrian Likins"]
license: "GPL-3.0-or-later"
readme: "README.md"
tags:
  - collectiontest
dependencies:
  geerlingguy.gitlab: '*'
  geerlingguy.java: '*'
  alikins.collection_inspect: '*'
  alikins.top_geerlingguy: '*'
