namespace: "alikins"
name: "collection_reqs_test"
version: "2.1113.12"
description: "a collection with requirements.yml"
authors: ["Adrian Likins"]
license: "GPL-3.0-or-later"
tags:
  - collectiontest
dependencies:
  geerlingguy.gitlab: '*'
