namespace: "alikins"
name: "collection_reqs_test"
version: "2.1113.34"
description: "a collection with some deps on other collections"
authors: ["Adrian Likins"]
license:
  - "GPL-3.0-or-later"
readme: "README.md"
tags:
  - collectiontest
dependencies:
  geerlingguy.gitlab: '*'
  alikins.collection_ntp: '*'
  alikins.collection_inspect: '*'
  alikins.top_geerlingguy: '*'
